header:
  - name: Galerie
    url: /fr/galerie
    weight: 1
  - name: Packages
    url: /fr/packages
    weight: 2
  - name: Documentation
    url: https://openfisca.org/doc/
    weight: 3
  - name: À propos
    url: /fr/a-propos
    weight: 4
  - name: Association
    url: /fr/association
    weight: 5
footer:
  - name: Mentions légales
    url: /fr/mentions-legales
    weight: 1
  - name: Données personnelles
    url: /fr/privacy
    weight: 2
  - name: Contactez-nous
    url: mailto:contact@openfisca.org?Subject=openfisca.org
    weight: 3
  - name: État des services
    url: https://stats.uptimerobot.com/A6WQWi553
    weight: 4
  - name: Améliorer ce site
    url: https://github.com/openfisca/openfisca.org/
    weight: 5
    identifier: contribute
