version: 2.1

orbs:
  hugo: circleci/hugo@1.3.0
  node: circleci/node@5.0.3

jobs:
  test:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Lint CSS
          command: npm run lint:css
      - run:
          name: Lint JavaScript
          command: npm run lint:js
      - run:
          name: Check showcase data
          command: npm run test:showcase

  html_validate:
    docker:
      - image: cimg/ruby:2.7.3-browsers
    steps:
      - checkout
      - run:
          name: Install html-proofer
          command: gem install html-proofer --version 4.4.3
      - attach_workspace:
          at: .
      - run:
          name: Check HTML common mistakes
          command: exec htmlproofer ./public --assume-extension .html --disable-external true --ignore-empty-alt true --allow-missing-href true

  deploy:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - attach_workspace:
          at: .
      - run:
          name: Publish to openfisca.org
          command: |
            touch public/.nojekyll # Bypass Jekyll processing on GitHub Pages
            git checkout gh-pages
            cp -R doc /tmp/doc
            git checkout -
            mv /tmp/doc public/doc
            npm run publish

workflows:
  version: 2
  main:
    jobs:
      - test
      - hugo/build:
          version: '0.108'
          html-proofer: false
          pre-steps:
            - checkout
            - node/install
            - run: npm ci
      - html_validate:
          requires:
            - hugo/build
      - deploy:
          requires:
            - test
            - hugo/build
            - html_validate
          filters:
            branches:
              only: main
