name = "OpenFisca 2022"
license = "MIT"
licenselink = "https://github.com/openfisca/openfisca.org/blob/master/themes/OpenFisca-2022/LICENSE"
homepage = "https://openfisca.org"
min_version = "0.101.0"
